### ISSUE TITLE
Anpassung der hr-Trennlinie: Abstand verringern und/oder Sichtbarkeit erhöhen

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-RWFak#10]
Die Trennlinien sind, je nach Monitor, kaum oder gar nicht zu sehen und besitzen einen relativ großen Abstand nach oben, wodurch sich ein übertrieben großer Abstand zwischen den beiden Content-Bereichen (oben und unten bzw. davor und danach) einstellt. (Siehe Anhang)

Könnte man hier entweder die Sichtbarkeit der Trennlinie erhöhen in dem man z.B. etwas Transparenz herausnimmt (je nach dem wie es umgesetzt worden ist) oder den Abstand nach oben und unten etwas verringern? 

![hr_rwfak](https://cloud.githubusercontent.com/assets/6545158/13703538/276d3c78-e797-11e5-92e8-ee7ae10d6cf9.png)

**Comment by AstridSemm** [comment]
Das geht nicht ohne größeren Aufwand; ich empfehle, zunächst den &lt;hr&gt;-Tag wegzulassen und einfach mit Absätzen zu arbeiten.

**Comment by xwolfde** [comment]
Muss gesondert geklärt werden. Ist keine technische Frage.
Siehe Mail.
