### ISSUE TITLE
Medien in Ordner verpacken

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-RWFak#17]
Das Büro für internationale Beziehungen hat in der bisherigen WP-Umgebung ein Plugin, das Medien in Ordner verschiebt (Media File Manager Advanced). Nachdem über dieses Plugin mehrere hundert Dokumente zugeordnet sind, würden sie das natürlich gern übernehmen und sind ein wenig enttäuscht, dass es eine solche Möglichkeit auf der Multisite-Instanz nicht gibt. Frage: Ist es möglich, dieses Plugin auf die Multisiteinstanz zu ziehen? Oder gäbe es theoretisch eine Möglichkeit, etwas ähnliches anzubieten? Dies alles natürlich auf lange Sicht; dass das kurzfristig nicht geht, ist klar.

**Comment by xwolfde** [comment]
Nein, das verfolgt das falsche Konzept der hierarischen Ordner in einem Medium, welches aufgrund der Direktverlinkungen keine Hierarchien hat. Von dem Konzept muss man sich trennen.
Wenn wir das Plugin einführen würden, würden wir es nicht mehr los werden und hätten dann immer einen Diskussionsbedarf und Probleme.

**Comment by AstridSemm** [comment]
Ok, danke. Das gebe ich dem Kunden dann mal weiter.

**Comment by AstridSemm** [comment]
Nachdem es für das Problem derzeit keine Lösung gibt, wird der issue mal geschlossen.
