### ISSUE TITLE
Farbe prüfen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-RWFak#2]
Vorschlag aus Merge-Request

**Comment by AstridSemm** [comment]
Ja, das sollten wir insgesamt prüfen. Einerseits ist das Rot des Social Media Menüs zu grell, andererseits ist der Kontrast bei manchen Mouseover-Aktionen zu gering. Screenshots:
![bildschirmfoto 2015-07-09 um 13 33 00](https://cloud.githubusercontent.com/assets/11296947/8594208/198abb0e-263f-11e5-8354-44091c55b7ba.png)

![bildschirmfoto 2015-07-09 um 13 33 19](https://cloud.githubusercontent.com/assets/11296947/8594213/1df937ba-263f-11e5-80b2-9be27b3445ac.png)

**Comment by xwolfde** [comment]
Wird beim nächsten Update behoben und für alle Fakultätsseiten vereinheitlicht auf Hintergrundfarbe helles Grau (wie oben Metanav) und Schriftfarbe Navy. Hoverfarbe ist Basecolor.
