### ISSUE TITLE
Slash in der Breadcrumb uneinheitlich

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-RWFak#22]
Ist mir heute zufällig aufgefallen beim Kunden, als ich das Format verkleinert habe auf Mobile. Ist aber natürlich immer da. Bitte mal prüfen und nachkorrigieren. In der Mobilen Ansicht erscheint Leerzeichen-Slash-Leerzeichen als zu viel, vor allem bei Umbrüchen. Keine Ahnung, was da Standard ist! 

![breadcrumb 1](https://cloud.githubusercontent.com/assets/11868989/14869196/32f65132-0cd2-11e6-87f3-19bb900b8dd9.jpg)

**Comment by xwolfde** [comment]
Die Slashes der Breadcrumb sind schon richtig. Die Seite selbst wurde allerdings ungeschickterweise mit einem Titel ausgestattet der auch ein Slash zwischen Habilitation und Postdocs hat:
https://www.wiso.rw.fau.de/forschung/wissenschaftlicher-nachwuchs/habilitationpostdocs/
Es handelt sich hier tatsächlich um eine Seite, nicht um eine Seite "Postdocs" unterhalb der Seite "Habilitation".

=> Der Autor sollte keine Slashes in dem Seitentitel verwenden.

**Comment by csw-** [comment]
Der Autor hat es zur Kenntnis genommen ;)
