### ISSUE TITLE
Unterschiedliche Überschriftsgrößen in Sidebar

### ISSUE THREAD

**Issue by csw-** [RRZE-Webteam/FAU-RWFak#23]
Die h2-Größen der "Titel oben"-Überschrift und "Titel erster Linkblock"-Überschrift sind ungleichmäßig. Bei ersterer hängt noch die CSS-Klasse "small" dran. (Beispiel: [https://career.cms.rrze.uni-erlangen.de/](https://career.cms.rrze.uni-erlangen.de/) ) 

Was ist denn hier der (Hinter)grund für die Entscheidung?  

![h2sidebar](https://cloud.githubusercontent.com/assets/6545158/15074971/53e507cc-13a2-11e6-8ee7-3a998da5d2c8.jpg)

**Comment by xwolfde** [comment]
ich **glaub** das ist einfach nur ein bug. 
eigentlich müsste da auch kein small hin, sondern das müsste automatisch kommen für Teile der Sidebar.

**Comment by xwolfde** [comment]
In der nächsten Version gefixt
