### ISSUE TITLE
Überschrift Kontakte in Sidebars

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-RWFak#3]
Ich denke, wir haben die Frage auch schon bezüglich MedFak und in meiner Testinstanz ist das reproduzierbar, also vermute ich, dass das über alle Themes geht: Es gibt die Möglichkeit, den Kontakten in der Sidebar eine Überschrift zu verpassen (im Screenshot: "Studiengangsverantwortlich").
![bildschirmfoto 2015-07-23 um 08 17 12](https://cloud.githubusercontent.com/assets/11296947/8844258/48ca54cc-3113-11e5-93b9-a40a2983b107.png)
Allerdings wird diese Überschrift im Frontend nicht angezeigt (ich habe das im Screenshot in rot hineingeschrieben):
![bildschirmfoto 2015-07-23 um 08 18 35 kopie](https://cloud.githubusercontent.com/assets/11296947/8844286/a1c3d12a-3113-11e5-811d-5af46af29833.png)
Ist das ein Bug oder ein feature?

**Comment by xwolfde** [comment]
Durch Änderung der Optionen in fau-person geändert und geklärt
