### ISSUE TITLE
Videos im Social Media Footer

### ISSUE THREAD

**Issue by ec89yler** [RRZE-Webteam/FAU-RWFak#39]
Hallo zusammen, die Videos im Social Media Footer sind plötzlich "zusammengeschoben", hier müsste wieder etwas Abstand dazwischen. Liegt das am Update auf 4.8?

![2017-07-11 10_05_52-fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/28057775-70c2d4dc-6621-11e7-8d31-43439d8e088c.png)

**Comment by xwolfde** [comment]
Ja, wir werden diese Woche noch ein neues Video-Plugin veröffentlichen, welches das Problem behebt und neue Features einführt.

**Comment by ec89yler** [comment]
Alles klar, vielen Dank für die Info!

**Comment by xwolfde** [comment]
Diese Woche = Heute. Das Plugin ist Abwärtskompatibel zu FAU Video und wird es ersetzen. Wir kümmern uns darum.
Neue Features sind bessere Performance und ANsicht des Videos in einem großen Modal anstelle dem kleinen fitzelchen unten :) 
Doku auf wordpress.rrze in Vorbereitung, bis dahin hier: https://github.com/RRZE-Webteam/rrze-video
