### ISSUE TITLE
Logos auf Lehrstuhlseiten

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/FAU-RWFak#43]
Bei mehreren Lehrstuhl-Websites war nach dem Update das Logo verschwunden, obwohl vorher das Default-Fachbereichs-Logo aus dem Theme ausgewählt war:
![test2](https://user-images.githubusercontent.com/28564104/31822465-312051ce-b5a9-11e7-8055-296d66eb7feb.jpg)

**Comment by xwolfde** [comment]
tl;dr: Das sollte inzwischen behoben sein.  Hab ich eine Site übersehen? Welche?


Ursache war, dass die Logos ja vorher "unscharf" waren. Daher wurden alle Logos mit 300dpi neu erstellt. Dadurch wiederum ging die Referenz verloren. 
Ich bin nach dem Update eigentlich alle Domains durchgegangen (bis vorhin) um überall da, wo das Fakultätslogo oder ein FB-Logo verwendet wurde wo eigentlich der Titel der Site hingehört, das neue Logo wieder einzustellen.
Grundsätzlich sollte aber wirklich kein Fakultätslogo oder gar das FAU-Logo an der Stelle sein.
