### ISSUE TITLE
WYSIWYG-Editor Sidebar

### ISSUE THREAD

**Issue by j-hofmann** [RRZE-Webteam/FAU-RWFak#5]
1. Eintrag in den Theme Options / Erweitert für "WYSIWYG-Editor Text unten" ist doppelt vorhanden
2. Typo im Text: "Sitebar" --> "Sidebar".
3. Funktion: Trotz WYSIWYG aktiviert werden manche Steuerzeichen nur bei Eingabe im HTML-Editor gespeichert, z.B. <p> oder </br>; Zeilenumbruch im WYSIWYG-Modus gar nicht.
4. Funktion II: Sobald dann wieder im WYSIWYG-Modus gearbeitet und erneut gespeichert wird, sind die <p>'s auch im html-Editor wieder weg...
Könnte ein Fehler mit der Blacklist oder valid_elements vom TinyMCE sein.
5. Funktion: wenn schon WYSIWYG, warum dann nicht den "vollen" TinyMCE mit allen Optionen wie im Beitragstext-Editor auch?

**Comment by xwolfde** [comment]
Typisch werden in der nächsten Verison korrigiert sein. Derzeit im Dev-Zweig bei FAU-Einrichtungen.

Es wird nur der "kleine" WYSIWYG-Editor verwendet, weil wir bei dem großen User-Probleme hatten. Ausserdem erscheint dfann die Auswahl der Mediathek mit vielen Möglichkeiten, wie auch der Gallerie etc pp. Diese Freiheit ist dort nicht erwünscht; Die gefahr, daß das Theme durch dieses Mehr an Möglichkeiten durch unbedarfte Redakteure kaputt gemacht wird, ist zu groß.
