### ISSUE TITLE
Top-Links brauchen Platz

### ISSUE THREAD

**Issue by aharth** [RRZE-Webteam/FAU-RWFak#50]
Links zu FAU Faculty of Business, Economics, and Law  Mein Campus UnivIS Map Search brauchen viel Platz. Zusammen mit Browserfenster,  Browser-Adressleiste und Banner ist 1/3 meines Bildschirms voll, und zwar immer, weil das Top-Banner fixiert ist.

Es waere super, wenn man den allgemeinen Bannerteil (also alles was blaugrau am oberen Ende der  Seite ist) als Konfigurations-Option ausschalten koennte.

Noch cooler ware, wenn es zusaetzlich eine Option gibt, mit der man die Fixierung des Banners ausschalten kann, so dass die Seite ganz normal scrollt.

Davon abgesehen bin ich mit dem Template sehr zufrieden.

Besten Dank,
Andreas.

**Comment by xwolfde** [comment]
An der Stelle des Kopfteils ist ein Umbau geplant. 
Demnach wird die Fakultät aus der Leiste entfernt und im Rahmen einer neuen ORGA-Breadcrumb eingeblendet.
Die ORGA-Breadcrumb wird dann automatisch erstellt und auch für EInrichtungen der Fakultäten nicht änderbar sein. Optionen werden wahrscheinlich nicht mehr zugelassen.
Im Gegenzug hat man mehr Platz ganz oben für eigene Links.

Auch die Suchmaske wird umgebaut. Es wird wahrscheinlich auch zu anderen Änderungen kommen. 
Prioritäten der anstehenden Änderungen sind:
- Suche
- Mobile Darstellung
- Orga Breadcrumb

Wesentliche Änderungsdiskussion aber am besten hier: 
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues
(Die Fakultätsthemes werden nur von den Einrichtungstheme abgeleitet.)
